access-company/antikythera

- mix.exs
https://acsmine.tok.access-company.com/redmine/issues/143354
> 143354_additional_cleanup_before_publish

- CHANGELOG.md
- core/async_job/queue.ex
- core/async_job/rate_limit.ex
- core/sup_tree_core/executor_pool/async_job_runner.ex
- lib/async_job/async_job.ex
- lib/test/async_job_helper.ex
- lib/test/gear_log_helper.ex
- lib/util/cron.ex
- mix.exs
- mix.lock
- test/core/async_job/queue_test.exs
- test/core/web/cookies_test.exs
- test/lib/util/cron_test.exs
https://acsmine.tok.access-company.com/redmine/issues/143632
> 143632 rate limit queries and commands to async job queues

- core/sup_tree_core/gear_config_poller.ex
https://acsmine.tok.access-company.com/redmine/issues/146113
> [146113] Implement handle_cast in GearConfigPoller

- core/ets/ets.ex
- core/ets/memcache.ex
- core/executor_pool/registered_name.ex
- core/sup_tree_core/executor_pool/executor_pool.ex
- core/sup_tree_core/executor_pool/memcache_manager.ex
- core/sup_tree_core/executor_pool/memcache_writer.ex
- lib/util/memcache.ex
- lib/util/term_util.ex
- test/core/sup_tree_core/executor_pool/executor_pool_test.exs
- test/lib/util/memcache_test.exs
- Store objects in ETS per epool_id
- Limit the number of objects and its each size
- Objects will be expired probabilistically (to avoid the thundering herd)
https://acsmine.tok.access-company.com/redmine/issues/133936
> [133936] Add Antikythera.Memcache as an in-memory cache storage

- CONTRIBUTING.md
- doc_src/library_dependencies.md
- mix.exs
- mix.lock
- mix_common.exs
https://acsmine.tok.access-company.com/redmine/issues/146611
> 146611_replace_dialyze_with_dialyxir

- .circleci/config.yml
- .tool-versions
https://acsmine.tok.access-company.com/redmine/issues/134454
> [134454] Upgrade Elixir: 1.5.3 => 1.6.6

- .tool-versions
- CHANGELOG.md
- doc_src/development_environment.md
- mix_common.exs
https://acsmine.tok.access-company.com/redmine/issues/146116
> 146116_quit_enforcing_erlang_elixir_versions

- priv/gear_template/test/web/controller/hello_test.exs
Moved the test for hello controller in generated gear, from gear_name_test.exs to web/controller/hello_test.exs.
> Move gear_name_test.exs to web/controller/hello_test.exs

- core/gear_log/file_handle.ex
- test/core/gear_log/file_handle_test.exs
https://acsmine.tok.access-company.com/redmine/issues/149372
> [149372] Remove utf-8 encoding specification

- lib/async_job/async_job.ex
Docs for https://github.com/access-company/antikythera/pull/24
https://acsmine.tok.access-company.com/redmine/issues/147879
> [147879] Add docs for :bypass_job_queue option in AsyncJob

- lib/util/httpc.ex
- test/lib/util/httpc_test.exs
https://acsmine.tok.access-company.com/redmine/issues/149859
> [149859] Fix to accept iolist in Httpc.ReqBody

- lib/type/string.ex
https://acsmine.tok.access-company.com/redmine/issues/151989
> [151989] Clarify restriction of TenantId

- CHANGELOG.md
- core/executor_pool/id.ex
- core/handler/executor_pool_helper.ex
- core/handler/gear_error.ex
- doc_src/gear_developers/controller.md
- lib/async_job/async_job.ex
- lib/gear_application/error_handler.ex
- lib/type/executor_pool.ex
https://acsmine.tok.access-company.com/redmine/issues/152374
> 152374 make error response for invalid epool id customizable

- lib/util/env.ex
To set `Content-Security-Policy` header in gear application.
I think test should be in testgear.
> Add Antikythera.Env.asset_base_url/1

- core/async_job/async_job.ex
- core/sup_tree_core/executor_pool/async_job_runner.ex
- test/core/async_job/queue_test.exs
- temporarily accept non-binary payload on async_job_runner due to hot upgrading
https://acsmine.tok.access-company.com/redmine/issues/133835
> [133835] treat payload of async jobs as binary internally

- lib/async_job/async_job.ex
https://acsmine.tok.access-company.com/redmine/issues/133835
> [133835] Add notices for large payloads in async_job doc

- core/mix/ensure_gear_dependencies.ex
- core/util/path.ex
- mix_common.exs
https://acsmine.tok.access-company.com/redmine/issues/156276
> [156276] enable to set local path as gear dependencies

- priv/gear_template/mix.exs
https://acsmine.tok.access-company.com/redmine/issues/156276
> [156276] Set deps dir as an environmental variable in gears' mix.exs

- core/sup_tree_core/executor_pool/executor_pool.ex
- test/core/sup_tree_core/executor_pool/usage_reporter_test.exs
https://acsmine.tok.access-company.com/redmine/issues/145131
> [145131] Change to use DynamicSupervisor instead of :simple_one_for_one option

- lib/mix/prepare_assets.ex
https://acsmine.tok.access-company.com/redmine/issues/146100
> [146100] Remove gulp entry point

- core/version/version.ex
- mix.exs
https://acsmine.tok.access-company.com/redmine/issues/169382
> [169382] Fix app acquisition at version check

- .circleci/config.yml
- .credo.exs
- .tool-versions
- core/mix/generate_release.ex
- lib/type/xml.ex
- lib/util/code_util.ex
- mix_common.exs
https://acsmine.tok.access-company.com/redmine/issues/150737
In ```.credo.exs``` I removed ```Credo.Check.Readability.PreferUnquotedAtoms``` and ```Credo.Check.Warning.LazyLogging``` because these checks are incompatible with elixir(1.7.0>=).
* https://github.com/rrrene/credo/blob/26afbaad9590db41b46d20252809db9a1d1590a4/CHANGELOG.md#0100
* https://github.com/rrrene/credo/blob/26afbaad9590db41b46d20252809db9a1d1590a4/CHANGELOG.md#103
> 150737 Upgrade elixir to v1.7.4

- core/alert/handler/handler.ex
- core/sup_tree_common/alert_manager.ex
- test/core/sup_tree_common/alert_manager_test.exs
https://acsmine.tok.access-company.com/redmine/issues/178266
> [178266] ignore alerts that match regexps specified in gear config

- core/handler/body_parser.ex
https://acsmine.tok.access-company.com/redmine/issues/178931
> [178931] Fix type error

- mix_common.exs
https://acsmine.tok.access-company.com/redmine/issues/179347
> [179347] Append extra compilers specified in Antikythera instances to mix.exs

- core/async_job/queue.ex
- lib/mix/gear_static_analysis.ex
- lib/web/template/precompiler.ex
Reverts access-company/antikythera#51
https://github.com/access-company/antikythera/pull/51#issuecomment-513077526
> Revert "[179864] fix credo error: large abc size"

- core/sup_tree_core/executor_pool/async_job_broker.ex
https://acsmine.tok.access-company.com/redmine/issues/182627
> Avoid unnecessary group addition

- lib/type/integer.ex
- lib/util/time.ex
https://acsmine.tok.access-company.com/redmine/issues/177930
> [177930] Add type check to Antikythera.Time

- core/mix/appup.ex
https://acsmine.tok.access-company.com/redmine/issues/183123
> Remove unchanged moduels from appup

- core/gear_log/file_handle.ex
https://acsmine.tok.access-company.com/redmine/issues/185147
> Check log write

- core/sup_tree_core/system_metrics_reporter.ex
- core/util/vm.ex
- test/core/util/vm_test.exs
https://acsmine.tok.access-company.com/redmine/issues/184651
> [184651] count messages in all mailboxes

- core/sup_tree_core/executor_pool/async_job_runner.ex
https://acsmine.tok.access-company.com/redmine/issues/185740
> [185740] Write log

- core/gear_log/file_handle.ex
- lib/util/string_format.ex
- lib/util/time.ex
https://acsmine.tok.access-company.com/redmine/issues/185702
> [185702] Avoid string interpolation

- core/sup_tree_core/system_metrics_reporter.ex
- mix.exs
- mix.lock
https://acsmine.tok.access-company.com/redmine/issues/185049
> [185049] log process with too many messages

- core/sup_tree_gear/gear_log_writer.ex
https://acsmine.tok.access-company.com/redmine/issues/185815
> [185815] Set off_heap to message_queue_data option of Logger process

- .tool-versions
> [185700] update Elixir to 1.8.2

- .tool-versions
Reverts access-company/antikythera#75
> Revert "[185700] update Elixir to 1.8.2"

- doc_src/getting_started.md
https://acsmine.tok.access-company.com/redmine/issues/169054
https://github.com/access-company/antikythera/issues/72
> [169054] Fix broken link

- core/core.ex
- core/gear_log/file_handle.ex
- core/sup_tree_core/reduction_log_writer.ex
- core/util/path.ex
- test/core/sup_tree_core/reduction_log_writer_test.exs
https://acsmine.tok.access-company.com/redmine/issues/186119
> [186119] Add reduction writer

- .circleci/config.yml
> [185700] (CI) Ensure Elixir version used by the previous antikythera is available

- .tool-versions
https://acsmine.tok.access-company.com/redmine/issues/187391
> [187391] update Elixir 1.8.2 -> 1.9.1

- CHANGELOG.md
- mix.exs
- mix_common.exs
https://acsmine.tok.access-company.com/redmine/issues/169054
This PR will resolves [this issue](https://github.com/access-company/antikythera/issues/72#issuecomment-531213422).
> [169054] Release v0.3.0 of hex package

- .credo.exs
https://acsmine.tok.access-company.com/redmine/issues/188672
> [188672] fix missing comma

- config/config.exs
- core/handler/gear_action/gear_action.ex
https://acsmine.tok.access-company.com/redmine/issues/186122
> [186122] Write `X-Amzn-Trace-Id` to log

- lib/util/fast_jason_encoder.ex
- lib/web/conn.ex
- test/lib/util/fast_json_encoder_test.exs
https://acsmine.tok.access-company.com/redmine/issues/134410
> [134410] Speed up Conn.json

- lib/util/fast_jason_encoder.ex
- test/lib/util/fast_json_encoder_test.exs
https://acsmine.tok.access-company.com/redmine/issues/190338
> [190338] Support MapSet

- core/mix/generate_release.ex
- core/version/gear.ex
- local/mix/version_upgrade_test.ex
- rel/boot_script.dev.patch
https://acsmine.tok.access-company.com/redmine/issues/189201
> [189201] embedded mode

- core/core.ex
https://acsmine.tok.access-company.com/redmine/issues/188978
> [188978] Add startup logs

- core/mix/generate_release.ex
- core/version/gear.ex
- test/core/version/gear_test.exs
https://acsmine.tok.access-company.com/redmine/issues/189201
> [189201] enable embedded mode

- core/sup_tree_core/stale_gear_artifact_cleaner.ex
https://acsmine.tok.access-company.com/redmine/issues/191740
> [191740] Change `StaleGearArtifactCleaner` interval

- lib/mix/prepare_assets.ex
https://acsmine.tok.access-company.com/redmine/issues/187499
> [187499] Detect insecure npm package

- priv/gear_template/web/template/layout/application.html.haml
https://acsmine.tok.access-company.com/redmine/issues/193807
> [193807] fix content value in gear template

- lib/mix/prepare_assets.ex
https://acsmine.tok.access-company.com/redmine/issues/187499
> [187499] Reject insecure NPM package

- .circleci/config.yml
- .tool-versions
https://acsmine.tok.access-company.com/redmine/issues/201030
> [201030] Update Erlang OTP 20.3.8.25

- doc_src/gear_developers/executor_pool.md
https://acsmine.tok.access-company.com/redmine/issues/201527
> Add description about executor_pool

- mix_common.exs
https://acsmine.tok.access-company.com/redmine/issues/176138
> [176138] instance dependency after tool dependencies

- .circleci/config.yml
- .tool-versions
https://acsmine.tok.access-company.com/redmine/issues/201527
> [201527] Upgrade Elixir to 1.9.4

- lib/mix/gear.new.ex
https://acsmine.tok.access-company.com/redmine/issues/200707
> [200707] Read antikythera instance's gear_templates dir

- core/sup_tree_core/termination_manager.ex
- core/sup_tree_gear/gear_log_writer.ex
https://acsmine.tok.access-company.com/redmine/issues/201083
> [201083] Flush gear's log on termination

- doc_src/gear_developers/async_job.md
- doc_src/gear_developers/executor_pool.md
- doc_src/gear_developers/g2g.md
- doc_src/gear_developers/i18n.md
- doc_src/library_dependencies.md
https://acsmine.tok.access-company.com/redmine/issues/203364
> [203364] revise some document pages

- core/sup_tree_core/termination_manager.ex
- core/sup_tree_gear/gear_log_writer.ex
This reverts commit 20bd015892900c0314f77a18c3934b337c5806c6.
> Revert "[201083] Flush gear's log on termination (#117)"

- core/sup_tree_core/termination_manager.ex
- core/sup_tree_gear/gear_log_writer.ex
Reverts access-company/antikythera#120
> Revert "Revert "[201083] Flush gear's log on termination (#117)""

- test/lib/test/config_test.exs
https://acsmine.tok.access-company.com/redmine/issues/201739
> [201739] Add a test case for blackbox_test_secret/0

- doc_src/gear_developers/testing.md
- lib/test/config.ex
- test/lib/test/config_test.exs
https://acsmine.tok.access-company.com/redmine/issues/201739
> [201739] Implement whitebox_test_secret/0

- core/web/cookies.ex
https://acsmine.tok.access-company.com/redmine/issues/181466
> Log invalid cookie

- core/gear_log/file_handle.ex
- doc_src/development_environment.md
- lib/util/env.ex
https://acsmine.tok.access-company.com/redmine/issues/202463
> [202463] Add ANTIKYTHERA_MIX_TASK_MODE

- core/cluster/node_id.ex
- core/gear_log/context_helper.ex
- core/web/context.ex
- eal/metrics_storage.ex
- lib/mix/task.ex
- lib/type/string.ex
- test/core/gear_log/context_helper_test.exs
- test/lib/mix/task_test.exs
https://acsmine.tok.access-company.com/redmine/issues/202670
> [202670] Mix task can set the ContextId in GearLog

- lib/util/fast_jason_encoder.ex
- test/lib/util/fast_json_encoder_test.exs
https://acsmine.tok.access-company.com/redmine/issues/206811
> 206811 fast jason encoder supports data time

- core/sup_tree_core/executor_pool/usage_reporter.ex
https://acsmine.tok.access-company.com/redmine/issues/200720
> [200720] Report usage more frequently

- core/handler/cowboy_routing.ex
- doc_src/development_environment.md
- doc_src/gear_developers/routing.md
- doc_src/getting_started.md
- lib/test/config.ex
- lib/util/env.ex
We no longer need to modify `/etc/hosts` for gear development.
https://acsmine.tok.access-company.com/redmine/issues/206806#note-5
> [206806] Allow access via localhost

- core/handler/cowboy_routing.ex
- doc_src/development_environment.md
- doc_src/gear_developers/routing.md
- doc_src/getting_started.md
- lib/test/config.ex
- lib/util/env.ex
Reverts access-company/antikythera#130
> Revert "[206806] Allow access via localhost"

- lib/util/aws/cloudfront_signed_url.ex
- test/lib/util/aws/cloudfront_signed_url_test.exs
https://acsmine.tok.access-company.com/redmine/issues/209104
> [209104] Add support for a custom policy to CloudfrontSignedUrl

- core/sup_tree_core/executor_pool/async_job_runner.ex
https://acsmine.tok.access-company.com/redmine/issues/209241
> [209241] Write log when AsyncJobRunner times out

- core/sup_tree_core/executor_pool/async_job_runner.ex
Reverts access-company/antikythera#134
> Revert "[209241] Write log when AsyncJobRunner times out"

- .circleci/config.yml
- .tool-versions
https://acsmine.tok.access-company.com/redmine/issues/209197#note-11
ref: https://github.com/access-company/antikythera_instance_example/pull/13
> [209197] Update Erlang to 20.3.8.26

- core/handler/websocket_state.ex
https://acsmine.tok.access-company.com/redmine/issues/209197
> 209197 output reason when disconnecting

- doc_src/gear_developers/controller.md
https://acsmine.tok.access-company.com/redmine/issues/212594
> [212594] Document about client timeout

- .circleci/config.yml
- .tool-versions
https://acsmine.tok.access-company.com/redmine/issues/212875#note-32
ref: https://github.com/access-company/antikythera_instance_example/pull/15
> [212875] Update Erlang OTP 20.3.8.26

- core/handler/gear_action/g2g.ex
- core/sup_tree_core/executor_pool/action_runner.ex
- core/sup_tree_core/executor_pool/async_job_runner.ex
https://acsmine.tok.access-company.com/redmine/issues/214986#note-10
> [214986] Fix for brutal exit reason changed from :killed to :kill

- core/gear_log/file_handle.ex
https://acsmine.tok.access-company.com/redmine/issues/215210#note-38
> [215210] change binwrite/1 to write/1 in write_debug_log/2

- core/cluster/cluster.ex
- core/executor_pool/registered_name.ex
- core/handler/websocket_state.ex
- core/mix/upload_new_asset_versions.ex
- core/util/gear_module.ex
- core/web/cookies.ex
- core/web/template_engine.ex
- lib/mix/gear_static_analysis.ex
- lib/test/config.ex
- lib/util/httpc.ex
- lib/web/router/impl.ex
- lib/web/router/reverse.ex
- lib/web/router/router.ex
- lib/web/websocket.ex
- local/node_name.ex
https://acsmine.tok.access-company.com/redmine/issues/218823#note-6
> [218823] Remove credo warning

- test/core/version/gear_test.exs
https://acsmine.tok.access-company.com/redmine/issues/218823#note-14
> [218823] Clean test output

- config/config.exs
- core/version/gear.ex
https://acsmine.tok.access-company.com/redmine/issues/219865
> [219865] Notify gear install time

- core/sup_tree_core/executor_pool/action_runner.ex
- core/sup_tree_core/executor_pool/async_job_runner.ex
https://acsmine.tok.access-company.com/redmine/issues/219519
> [219519] Write error log when gear process is killed

- core/executor_pool/tenant_setting.ex
https://acsmine.tok.access-company.com/redmine/issues/220239?#note-2
> Remove a comment depended on sazabi

- core/handler/gear_action/g2g.ex
- core/version/gear.ex
https://acsmine.tok.access-company.com/redmine/issues/219519
ref: #157
> [219519] Write error log when gear-to-gear process is killed

- core/cluster/cluster.ex
Since the incident is over, I will revert access-company/antikythera#163.
**To reviewers:**
This change is a revert so you don't need to read the code.
But please approve this pull request if you agree with this reverting.
> Revert "Connect only InService instance"

- CHANGELOG.md
- core/core.ex
- core/sup_tree_core/termination_manager.ex
- eal/cluster_configuration.ex
- mix.exs
- test/core/core_test.exs
https://acsmine.tok.access-company.com/redmine/issues/222439#note-29
rel: https://github.com/access-company/antikythera_aws/pull/8
> 222439 Decide retry count dinamically for establish_connections_to_other_nodes/1

- mix.exs
https://acsmine.tok.access-company.com/redmine/issues/222439
> [222439] Bump the a9a version from v0.4.0 to v0.4.1

- lib/util/env.ex
- test/lib/util/env_test.exs
https://gate.tok.access-company.com/redmine/issues/220238
> [220238] Add `Antikythera.Env.base_url/1`

- core/config/gear.ex
- test/core/config/gear_test.exs
https://acsmine.tok.access-company.com/redmine/issues/222104#note-21
> [222104] Add a new field to gear config

- core/util/erlang_log_translator.ex
- test/core/util/erlang_log_translator_test.exs
https://acsmine.tok.access-company.com/redmine/issues/157956#note-44
> [157956] Make AntikytheraCore.ErlangLogTranslator compatible with Erlang/OTP 21+

- core/sup_tree_core/periodic_log/message_builder.ex
- test/core/sup_tree_core/periodic_log/message_builder_test.exs
- test/core/sup_tree_core/periodic_log/reduction_builder_test.exs
https://acsmine.tok.access-company.com/redmine/issues/157956#note-45
> [157956] Don't get :messages from Process.info/1 to be compatible with Erlang/OTP 21+

- config/config.exs
- mix.exs
https://acsmine.tok.access-company.com/redmine/issues/185234#note-19
> [185234] Adds more applications via config

- .circleci/config.yml
- .tool-versions
https://acsmine.tok.access-company.com/redmine/issues/235114#note-6
> [235114] Specify OTP version used for compiling elixir in .tool-versions

- core/gear_log/file_handle.ex
- core/gear_log/log_rotation.ex
- core/handler/gear_error.ex
- core/sup_tree_gear/gear_log_writer.ex
- doc_src/development_environment.md
- test/core/sup_tree_gear/gear_log_writer_test.exs
https://acsmine.tok.access-company.com/redmine/issues/233108#note-12
> [233108] Improve gear error output in test env

- .circleci/config.yml
- .tool-versions
- core/handler/gear_action/g2g.ex
- core/sup_tree_core/executor_pool/action_runner.ex
- core/sup_tree_core/executor_pool/async_job_runner.ex
https://acsmine.tok.access-company.com/redmine/issues/157956#note-68
> [157956] Upgrade Erlang/OTP to 22.3.4.21

- lib/test/config.ex
https://acsmine.tok.access-company.com/redmine/issues/238856#note-6
> [238856] Set long timeout to :module_load_timeout option

- core/util/gear_module.ex
- lib/test/config.ex
https://acsmine.tok.access-company.com/redmine/issues/239326#note-2
> [239326] Stop gear's supervisor after mix test to ensure closing gear's log file

- core/config/gear.ex
https://acsmine.tok.access-company.com/redmine/issues/238866
> [238866] Temporally add log for Config.Gear.read/1 error

- core/config/core.ex
- core/config/gear.ex
- core/executor_pool/tenant_setting.ex
- core/util/file_setup.ex
https://acsmine.tok.access-company.com/redmine/issues/238866
> [238866] Try to fix reading a half-written conf by :sync write/3

- mix.exs
https://acsmine.tok.access-company.com/redmine/issues/240044#note-2
> [240044] Use Code.require_file/1 instead of Code.load_file/1

- core/config/core.ex
- core/config/gear.ex
- core/executor_pool/tenant_setting.ex
- core/util/path.ex
https://acsmine.tok.access-company.com/redmine/issues/238866
> [238866] Atomically write conf and settings using rename

- core/handler/body_parser.ex
https://acsmine.tok.access-company.com/redmine/issues/241465
> [241465] Don't parse JSON body if Content-Encoding is specified

- lib/web/plug/content_decoding.ex
https://gate.tok.access-company.com/redmine/issues/241420
> [241420] Plug to decode gzipped request body

- core/config/gear.ex
https://acsmine.tok.access-company.com/redmine/issues/241759#note-13
> Revert "[238866] Temporally add log for Config.Gear.read/1 error (#188)"

- doc_src/gear_developers/deployment.md
https://acsmine.tok.access-company.com/redmine/issues/200084#note-28
> [200084] Remove document about git server

- core/mix/appup.ex
- core/version/gear.ex
https://acsmine.tok.access-company.com/redmine/issues/243759#note-4
> [243759] Do not delete auto generated module in appup

- core/mix/appup.ex
- core/version/gear.ex
https://acsmine.tok.access-company.com/redmine/issues/243759#note-11
> [243759] Do not use delete_module instruction in appup

- mix.exs
- mix.lock
https://acsmine.tok.access-company.com/redmine/issues/244082
> [244082] Remove unused library mox

- lib/util/time.ex
- test/lib/util/time_test.exs
https://acsmine.tok.access-company.com/redmine/issues/200297#note-16
> [200297] Antikythera.Time.new/1 should also be an identity mapping

- mix.exs
https://acsmine.tok.access-company.com/redmine/issues/239877#note-11
> [239877] Make pbkdf2 test only dependency

- lib/web/session/cookie.ex
- test/core/sup_tree_common/metrics_uploader_test.exs
https://acsmine.tok.access-company.com/redmine/issues/239880#note-9
> [239880] Prepare for migration to Elixir 1.10.4 

- core/core.ex
- core/handler/websocket_state.ex
- core/sup_tree_core/executor_pool/action_runner.ex
- core/sup_tree_core/executor_pool/async_job_runner.ex
- core/util/erlang_log_translator.ex
- core/util/gear_task.ex
- core/version/gear.ex
- core/web/conn.ex
- mix_common.exs
- rel/vm.args
- test/core/sup_tree_common/alert_manager_test.exs
https://acsmine.tok.access-company.com/redmine/issues/239881#note-21
> [239881] Prepare for migration to Elixir 1.11.4

- lib/util/httpc.ex
https://acsmine.tok.access-company.com/redmine/issues/255215
> [255215] Detect URL with empty path

- .tool-versions
https://acsmine.tok.access-company.com/redmine/issues/239881
> [239881] Upgrade Elixir: 1.9.4 → 1.11.4

- core/handler/gear_error.ex
- lib/mix/gear.new.ex
- lib/mix/gear_static_analysis.ex
- lib/web/router/impl.ex
https://acsmine.tok.access-company.com/redmine/issues/255083#note-1
> [255083] Fix some Credo warnings

- core/core.ex
- core/version/core.ex
https://acsmine.tok.access-company.com/redmine/issues/258506
> [258506] Add ErlangLogTranslator again after hotcode upgrading core

- .circleci/config.yml
https://acsmine.tok.access-company.com/redmine/issues/260327
> [260327] Change cert of github host key

- core/mix/generate_release.ex
- lib/test/config.ex
https://acsmine.tok.access-company.com/redmine/issues/260327
> [260327] resolve todo comments

- core/handler/cowboy_routing.ex
- core/handler/system_info_exporter.ex
https://acsmine.tok.access-company.com/redmine/issues/243004
> [243004] Add upgradability checker

- CONTRIBUTING.md
- README.md
- STYLE_GUIDE.md
- doc_src/development_environment.md
- doc_src/gear_developers/dynamic_html.md
- doc_src/gear_developers/testing.md
- doc_src/library_dependencies.md
https://acsmine.tok.access-company.com/redmine/issues/262321
> [262321] Update hyperlinks

- core/web/template_engine.ex
- lib/util/crypto.ex
- test/lib/util/crypto_test.exs
https://acsmine.tok.access-company.com/redmine/issues/239882
> [239882] Prepare for upgrading Elixir to 1.12

- test/lib/util/httpc_test.exs
https://acsmine.tok.access-company.com/redmine/issues/260138
> [260138] Add a test case for the error value in Httpc.post/4

- config/config.exs
- mix_common.exs
https://acsmine.tok.access-company.com/redmine/issues/239901
> [239901] Use `Config` instead of deprecated `Mix.Config`

- core/sup_tree_core/executor_pool/action_runner.ex
- core/web/conn.ex
- test/core/web/conn_test.exs
https://acsmine.tok.access-company.com/redmine/issues/169945
> [169945] Raise if a status code, which must not have body, has body

- .tool-versions
- core/handler/executor_pool_helper.ex
- core/handler/websocket_state.ex
- core/sup_tree_core/executor_pool/async_job_runner.ex
- core/web/cookies.ex
- lib/async_job/async_job.ex
- lib/gear_application/error_handler.ex
- lib/mix/gear.new.ex
- lib/test/config.ex
- lib/type/string.ex
- lib/type/xml.ex
- lib/util/aws/cloudfront_signed_url.ex
- lib/web/asset.ex
- lib/web/router/impl.ex
- lib/web/template/precompiler.ex
https://acsmine.tok.access-company.com/redmine/issues/239901
> [239901] Upgrade Elixir: 1.11.4 → 1.13.4

- core/handler/gear_action/web.ex
https://acsmine.tok.access-company.com/redmine/issues/265096
> [265096] Fix handling ping with payload in websocket

- .markdownlint-cli2.yaml
- CONTRIBUTING.md
- doc_src/development_environment.md
- doc_src/gear_developers/i18n.md
- doc_src/gear_developers/logging.md
- doc_src/getting_started.md
- doc_src/library_dependencies.md
- priv/gear_template/README.md
https://acsmine.tok.access-company.com/redmine/issues/271111
```shell
npm install markdownlint-cli2 --global
markdownlint-cli2 --fix "**/*.md"
```
😊
> [271111] Introduce markdownlint and fix errors

- CONTRIBUTING.md
https://acsmine.tok.access-company.com/redmine/issues/271111
> [271111] Clarify commands before sending PR

- lib/mix/prepare_assets.ex
https://acsmine.tok.access-company.com/redmine/issues/283415
> [283415] Fix document about prepare_assets

- CONTRIBUTING.md
https://acsmine.tok.access-company.com/redmine/issues/284344
> [284344] Fix broken link

- mix.exs
https://acsmine.tok.access-company.com/redmine/issues/284344
Reviews will be skipped because the change is already reviewed in #250.
> [284344] Bump up version to 0.5.1

- mix.exs
https://acsmine.tok.access-company.com/redmine/issues/284344
> [284940] Fix links to GitHub in docs

- mix_common.exs
https://acsmine.tok.access-company.com/redmine/issues/284940
> [284940] Add an option which specifies :docs to GearProject

- mix.exs
https://acsmine.tok.access-company.com/redmine/issues/284940
I'll merge this without review because it just update the version numbers.
> [284940] Bump up version to 0.5.1

- mix.exs
https://acsmine.tok.access-company.com/redmine/issues/284940
> [284940] Bump up version for development

- .formatter.exs
- mix_common.exs
https://acsmine.tok.access-company.com/redmine/issues/200297
> [200297] Apply mix format to mix_common.exs

- CHANGELOG.md
- core/web/template_engine.ex
- mix_common.exs
https://acsmine.tok.access-company.com/redmine/issues/179864#note-26
> [179864] Require Elixir ~> 1.13

- core/config/gear.ex
- core/handler/gear_action/web.ex
- core/metrics/aggregate_strategy.ex
- core/sup_tree_core/executor_pool/websocket_connections_counter.ex
- core/util/gear_module.ex
- lib/web/router/router.ex
- test/core/web/conn_test.exs
https://acsmine.tok.access-company.com/redmine/issues/179864#note-27
> [179864] Fix credo warnings which require little code change

- core/version/gear.ex
https://acsmine.tok.access-company.com/redmine/issues/179864#note-29
> [179864] Avoid negated conditions in if else blocks

- core/async_job/queue.ex
https://acsmine.tok.access-company.com/redmine/issues/179864#note-31
> [179864] Fix credo warnings in core/async_job/queue.ex

- lib/mix/gear_static_analysis.ex
- test/lib/mix/gear_static_analysis_test.exs
https://acsmine.tok.access-company.com/redmine/issues/179864#note-30
> [179864] Fix credo warnings in gear_static_analysis.ex

- lib/mix/prepare_assets.ex
- lib/web/asset.ex
- lib/web/template/precompiler.ex
https://acsmine.tok.access-company.com/redmine/issues/179864#note-33
> [179864] Fix credo warnings on complexity of asset and template functions

- core/sup_tree_core/system_metrics_reporter.ex
- lib/util/cron.ex
- test/core/sup_tree_core/system_metrics_reporter_test.exs
https://acsmine.tok.access-company.com/redmine/issues/179864#note-34
> [179864] Fix remaining credo warnings on complex functions

- core/executor_pool/tenant_setting.ex
- core/handler/cowboy_req.ex
- lib/type/xml.ex
- lib/web/router/impl.ex
https://acsmine.tok.access-company.com/redmine/issues/179864#note-35
> [179864] Fix credo warnings on appending single item to list

- core/alert/handler/handler.ex
- core/async_job/async_job.ex
- core/async_job/queue.ex
- core/config/gear.ex
- core/executor_pool/setting.ex
- core/executor_pool/tenant_setting.ex
- core/gear_log/log_rotation.ex
- core/handler/helper_modules.ex
- core/handler/websocket_state.ex
- core/sup_tree_core/error_counts_accumulator.ex
- core/sup_tree_core/executor_pool/async_job_broker.ex
- core/sup_tree_core/periodic_log/writer.ex
- core/sup_tree_core/termination_manager.ex
- core/sup_tree_core/tmpdir_tracker.ex
- core/sup_tree_gear/gear_log_writer.ex
- core/version/history.ex
- eal/alert_mailer.ex
- lib/type/async_job.ex
- lib/type/context.ex
- lib/type/g2g.ex
- lib/type/http.ex
- lib/type/xml.ex
- lib/util/cron.ex
- lib/util/httpc.ex
- lib/util/time.ex
- lib/web/conn.ex
- lib/web/session/session.ex
- test/lib/util/time_test.exs
https://acsmine.tok.access-company.com/redmine/issues/200297#note-36
> [200297] Remove recursive_new? options which became unnecessary with new croma

- priv/gear_template/test/web/controller/api/hello_test.exs
- priv/gear_template/test/web/controller/hello_test.exs
- priv/gear_template/web/controller/api/hello.ex
- priv/gear_template/web/controller/hello.ex
- priv/gear_template/web/router.ex
https://acsmine.tok.access-company.com/redmine/issues/289509
> [289509] Add parameter validation to gear template

- lib/test/openapi_assert_helper.ex
https://acsmine.tok.access-company.com/redmine/issues/289510
> [289510] Add more $ref support to OpenApiAssertHelper

- priv/gear_template/doc/api/api.yaml
- priv/gear_template/test/test_helper.exs
- priv/gear_template/test/web/controller/api/hello_test.exs
https://acsmine.tok.access-company.com/redmine/issues/289510
> [289510] Add OpenApiAssertHelper to the gear template

- core/type/base_param_struct.ex
- core/util/body_json_common.ex
- lib/web/plug/params_validator.ex
https://acsmine.tok.access-company.com/redmine/issues/289509
> [289509] Fix compilation error when modules in BodyJsonStruct cannot be loaded

- lib/util/crypto.ex
- lib/util/ip_address.ex
- mix_common.exs
https://acsmine.tok.access-company.com/redmine/issues/265199
> [265199] Fix deprecations in Elixir 1.14

- mix.exs
- mix.lock
https://acsmine.tok.access-company.com/redmine/issues/291344
> [291344] Update to the forked calliope

- core/mix/appup.ex
- core/mix/generate_release.ex
- core/util/erlang_log_translator.ex
- core/version/core.ex
- lib/util/fast_jason_encoder.ex
- local/running_environment.ex
- mix_common.exs
> [265200] Fix error in Elixir 1.15

- .tool-versions
- core/async_job/rate_limit.ex
- core/handler/executor_pool_helper.ex
- core/handler/gear_action/gear_action.ex
- core/handler/gear_error.ex
- core/handler/system_info_exporter.ex
- core/handler/websocket_state.ex
- core/version/gear.ex
- lib/util/memcache.ex
- lib/web/plug/ip_filtering.ex
- test/lib/type/param_string_struct_test.exs
> [265200] Upgrade Elixir to 1.15

- local/running_environment.ex
> [265200] dereference_symlinks when create the updated gear

- mix_common.exs
> [265200] Run :ex_doc app for mix docs

- local/mix/upgrade_compatibility_test.ex
> [265200] Clean whole build_dir before generating release in test

- local/mix/upgrade_compatibility_test.ex
> [265200] Clean local build_dir in the upgrading test

- CHANGELOG.md
- mix.exs
> [265200] Bump up version for development

- core/handler/cowboy_req.ex
- core/handler/gear_action/context.ex
- core/handler/gear_action/g2g.ex
- core/handler/gear_action/gear_action.ex
- core/handler/gear_action/web.ex
- core/sup_tree_core/executor_pool/async_job_runner.ex
- core/util/end_time.ex
- lib/util/time.ex
https://acsmine.tok.access-company.com/redmine/issues/309245
> [309245] Use monotonic time to calculate processing time

- lib/web/router/router.ex
https://acsmine.tok.access-company.com/redmine/issues/308633
> [308633] Doc: Fix description of per-API timeout

- .circleci/config.yml
https://acsmine.tok.access-company.com/redmine/issues/310948
> [310948] Save asdf plugins which are installed under ~/.asdf in CircleCI

- .circleci/config.yml
- .tool-versions
https://acsmine.tok.access-company.com/redmine/issues/310948
> [310948] Upgrade Erlang/OTP to 26.2.5.14
