CHANGELOG.md, README.md, mix.exs
- Include missing `.tool-versions` in hex package, as it is currently required by erlang/elixir version checks in mix_common.exs
(https://acsmine.tok.access-company.com/redmine/issues/143354)
=> 143354_add_tool-versions_to_hex_package

core/gear_log/file_handle.ex, core/web/request.ex, lib/type/async_job.ex, lib/type/http.ex, lib/type/string.ex, lib/web/router/impl.ex, lib/web/router/router.ex, local/mix/version_upgrade_test.ex
- use "\A" and "\z" instead of "^" and "$"
- use "~R" when there are no interpolations
Ticket: https://acsmine.tok.access-company.com/redmine/issues/133779
=> [133779] Refactoring about regex

core/sup_tree_core/termination_manager.ex, core/sup_tree_core/version_upgrade_task_queue.ex
- Add function to enable / disable upgrade of antikythera instance or gears in VersionUpgradeTaskQueue
https://acsmine.tok.access-company.com/redmine/issues/145135
=> [145135] Disable gear upgrades when a node recognizes that it's about to be terminated

core/config/core.ex, core/ets/system_cache.ex, core/executor_pool/setting.ex, core/executor_pool/tenant_setting.ex, core/executor_pool/ws_connections_capping.ex, core/sup_tree_core/core_config_poller.ex, core/util/os_util.ex, test/core/executor_pool/setting_test.exs, test/core/sup_tree_core/tenant_executor_pools_manager_test.exs
https://acsmine.tok.access-company.com/redmine/issues/157910
=> [157910] Cap `ws_max_connections` in gear/tenant exec pool settings based on available system memory

core/sup_tree_core/tmpdir_tracker.ex, lib/util/zip.ex, test/core/sup_tree_core/tmpdir_tracker_test.exs, test/lib/util/zip_test.exs
https://acsmine.tok.access-company.com/redmine/issues/177185
Abstract:
Implemented a wrapper module for `zip` shell command.
Purpose:
To add feature to generate password-encrypted ZIP file from a *gear*.
I chose to use shell command because it is the only cost-effective way which can suffice such a feature.
Limitations:
Along with newly utilizing a shell command, it is aided with limited permission to the local file systems.
In detail,
I added an interface `AntikytheraCore.TmpdirTracker.get/1` to get the path to currently used `tmpdir`.
After applying this interface, it is ensured:
- that it can be called from only within `Tmpdir.make/2` call,
- that the path for input file/directory is under `tmpdir`,
- that the path for resulting archive is under `tmpdir`.
I appreciate your suggestions.
=> [177185] Wrapper library for zip

.circleci/config.yml
https://acsmine.tok.access-company.com/redmine/issues/177185
Fixed CircleCI config to install `zip` command in test environment.
Blackbox tests for `Antikythera.Zip`, previously added in #44, has been failed because `zip` command was not found on CircleCI environment.
=> [177185] Compensate zip command in CircleCI

core/metrics/aggregate_strategy/time_distribution.ex, core/mix/generate_release.ex, lib/util/cron.ex, lib/util/httpc.ex, lib/util/time.ex, local/mix/upgrade_compatibility_test.ex, local/mix/version_upgrade_test.ex
ticket: https://acsmine.tok.access-company.com/redmine/issues/179864
This commit passes `mix credo --strict` for the below seven files:
* `lib/util/cron.ex`
* `lib/util/httpc.ex`
* `local/mix/version_upgrade_test.ex`
* `local/mix/upgrade_compatibility_test.ex`
* `core/metrics/aggregate_strategy/time_distribution.ex`
* `core/mix/generate_release.ex`
* `lib/util/time.ex`
Now all the Credo errors of `Function is too complex` have been resolved combining with https://github.com/access-company/antikythera/pull/51.
=> [179864] Fix credo error: Function is too complex

core/async_job/queue.ex, lib/mix/gear_static_analysis.ex, lib/web/template/precompiler.ex
ticket: https://acsmine.tok.access-company.com/redmine/issues/179864
This commit passes `mix credo --strict` for the below three files:
* `lib/mix/gear_static_analysis.ex`
* `lib/web/template/precompiler.ex`
* `core/async_job/queue.ex`
Most of the changes are deconstruction of `cond` and `case` in a function by defining same-name functions distinguished by pattern-matching (like overloading); These changes are for reducing ABC size of functions.
=> [179864] fix credo error: large abc size

core/async_job/queue.ex, lib/mix/gear_static_analysis.ex, lib/web/template/precompiler.ex
ticket: https://acsmine.tok.access-company.com/redmine/issues/179864
This PR is revised version of #51.
Only one change from #51 is mentioned in https://github.com/access-company/antikythera/commit/2328b92c87a1542a71e9906119340238a9038662#r34391893.
Using `Module.safe_concat/1` here throws `ArgumentError` when a resulting module name includes alias(es) and is used in only type specification.
I guess that atoms for such module names won’t be created at compile time because they won’t be used; Elixir requires such module names for only static analysis.
I think that we can safely skip a check for a module throwing `ArgumentError` because the module is actually used elsewhere, and Antikythera can detect problems there.
=> 179864 credo large abc size revised

mix.exs
Exclude `.tool-versions` from package contents because it is no longer required to use antikythera.
=> [185700] exclude .tool-versions from package contents

.circleci/config.yml
Get elixir version from [this file](https://github.com/access-company/antikythera_instance_example/blob/master/.tool-versions) rather than update manually.
=> [185700] Get elixir version from antikythera's `.tool-versions` in CircleCI workflow

.tool-versions, core/web/template_engine.ex
From Elixir 1.8, internal implementations of EEx.Engine have been changed (see the below PR).
https://github.com/elixir-lang/elixir/pull/8413
To follow this change, I modified `AntikytheraCore.TemplateEngine` which `use`s `EEx.Engine`.
=> [185700] update Elixir 1.7.4 -> 1.8.2

core/mix/propagate_file_modifications.ex, lib/mix/gear_static_analysis.ex, mix_common.exs
Antikythera now requires at least version 1.8 of Elixir because [changes in `AntikytheraCore.TemplateEngine`](https://github.com/access-company/antikythera/pull/79/commits/6b0b81e09575fff99dcfa9a295d252200ea23a53) are not backward compatible.
=> [185700] 185700 update least elixir version: `~> 1.6` -> `~> 1.8`

lib/util/map_util.ex
https://acsmine.tok.access-company.com/redmine/issues/187391
`Map.take/2`'s second argument now should be a list.
https://github.com/elixir-lang/elixir/blob/v1.9/CHANGELOG.md#elixir-3
This PR works on both Elixir 1.8 and 1.9.
=> [187391] `Map.take/2` should take list (preperation for Elixir 1.9)

.circleci/config.yml
https://acsmine.tok.access-company.com/redmine/issues/187400
To reflect changes in antikythera_instance_example and testgear repositories without updating antikythera itself, I use an ID of CircleCI workflow in cache names of their repositories.
=> [187400] use `CIRCLE_WORKFLOW_ID` in cache name of other repositories

core/mix/propagate_file_modifications.ex, lib/mix/gear_static_analysis.ex
https://acsmine.tok.access-company.com/redmine/issues/187391
From Elixir 1.8, `Mix.Task.Compiler.run/1` should return a tuple like the below.
```elixir
{:ok | :noop | :error, [Mix.Task.Compiler.Diagnostic.t()]}
```
=> [187391] fix return value of `Mix.Task.Compiler.run/1`

.circleci/config.yml
https://acsmine.tok.access-company.com/redmine/issues/187400
Ensure installation of an Elixir version previously used by antikythera when update of `.tool-versions` is detected; this is useful only in a case of ASDF cache being deleted...
=> 187400 prepare previous elixir

lib/util/cron.ex, test/lib/util/cron_test.exs
Recently I found a bug in `Antikythera.Cron.next/2` function when giving it a **month only** CRON expression like `* * * 12 *`, for example:
```elixir
alias Antikythera.{Cron, Time}
Cron.parse!("* * * 12 *") |> Cron.next({Time, {2020, 1, 1}, {0, 0, 0}, 0})
```
But if giving expression like `1 * * 12 *`, `* 1 * 12 *`, or `* * * 12 1`, it works well.
So I made some changes to fix this bug.
=> Fix `Antikythera.Cron.next/2` function

lib/util/fast_jason_encoder.ex, lib/web/conn.ex
In my project, `FastJsonEncoder.encode!/1` will be useful.
I didn't write additional tests for `encode!/1` because `encode/1` is tested.
=> Define `FastJsonEncoder.encode!/1`

.circleci/config.yml, .tool-versions
Reverts access-company/antikythera#139
Revert commit because testgear's test is not stable
=> Revert "[209197] Update Erlang to 20.3.8.26"

core/sup_tree_core/version_synchronizer.ex, core/version/gear.ex, test/core/version/gear_test.exs
https://acsmine.tok.access-company.com/redmine/issues/216773
Antikythera returns healthy to healthy API even if there is no running gear.  Generally speaking, this in not healthy.
`Version.Gear.install_gears_at_startup/1` returns :error if equal or less than half of gears are installed. Then, `AntikytheraCore.VersionSynchronizer.install_gears/0` try to match it with `:ok`. This won't call `StartupManager.all_gears_installed/0` which makes Antikythera healthy state.
=> [216773] Throw MatchError if about half of gears are not installed

core/cluster/cluster.ex
Due to a failure, change to connect only to healthy instances.
=> Connect only InService instance

core/gear_log/file_handle.ex, lib/util/httpc.ex
https://acsmine.tok.access-company.com/redmine/issues/222347#note-8
If there are hundreds of thousands of requests per minute to a gear, the size of the log file increase several tens of MB and may exceed the max body size limit.
So,
- I suggest increasing the max body size limit.
- I also suggest shortening the size check interval to reduce the rapid increase in log file size.
=> [222347] Change parameters to handle larger gear log size

core/util/erlang_log_translator.ex
https://acsmine.tok.access-company.com/redmine/issues/157956#note-84
=> [157956] Remove migration code used when upgrading to Erlang 21+

lib/web/plug/session.ex
This is related to #186 (specifically "Add an interface to `Antikythera.Plug.Session.load/2`"), but it stems from a different purpose, where we needed to explicitly set the expiration period of the session cookie.
This enables the gear to specify the behavior of the session cookie via the keyword list passed to the plug.
- Type signature of `load/2` 's `opts` variable. The keyword list should accept a map (which is passed to `make_before_send/3`), but this specification might be too broad
- Note: I have ran `mix dialyzer` and got no warnings
- Are there any test codes relating to this specific code?
- What to do if store is not a cookie?
=> Read Set-Cookie header options from Session plug's options

mix_common.exs
https://acsmine.tok.access-company.com/redmine/issues/239881#note-78
* * *
* To avoid inclusion of consolidated protocol information in the core PLT file in Elixir 1.11+.
* In Elixir 1.11+, dialyxir becomes to make a core PLT file with project-specific consolidated protocol information.
* Maybe [this commit](/elixir-lang/elixir/commit/4bd3c9936ba4d6d72b662655bfd4ab7c5a283e0a) caused it.
* In other words, the core PLT file is rewritten for each type checking.
* It fails if the operator (e.g. CI/CD tool) does not have write permission for the file.
* Disabling protocol consolidation resolves this issue.
* There seems  to be no performance degradation in release.
* Release builds of Antikythera have not used protocol consolidation for a long time.
=> [239881] Disable protocol consolidation

core/alert/handler/email.ex, core/executor_pool/registered_name.ex, core/handler/cowboy_routing.ex, core/handler/gear_action/gear_action.ex, core/handler/gear_error.ex, core/util/path.ex, core/version/gear.ex, lib/test/config.ex, lib/util/env.ex
https://acsmine.tok.access-company.com/redmine/issues/258506
This fixes [Credo.Check.Warning.ApplicationConfigInModuleAttribute](https://hexdocs.pm/credo/Credo.Check.Warning.ApplicationConfigInModuleAttribute.html)
=> [258506] Use compile_env instead of fetch_env or get_env during compiling

CHANGELOG.md, mix.exs
https://acsmine.tok.access-company.com/redmine/issues/284344
After merging this, I will do the following:
- `git tag 0.5.0 <commit hash>`
- `git push origin 0.5.0`
- `mix hex.publish`
- Fix [this line](https://github.com/access-company/antikythera/blob/16f189b2f3c53df340fb2ca3150174d1b43c4b4f/mix.exs#L44) by `version: Antikythera.MixCommon.version_with_last_commit_info("0.5.1"),`
- Update [antikythera_aws](/access-company/antikythera_aws)
=> [284344] Bump up version to 0.5.0

.circleci/config.yml, core/cluster/cluster.ex
https://acsmine.tok.access-company.com/redmine/issues/179864#note-38
=> [179864] Enable static analysis in CircleCI
